image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
branches:
  only:
  - master
build_script:
  - ps: . ./build.ps1
deploy: off
test: off
cache:
- tools -> build.cake
- packages -> build.cake